chore: Bump the runtime-dependencies group with 2 updates (#534)
Bumps the runtime-dependencies group with 2 updates:
[psycopg](https://github.com/psycopg/psycopg) and
[singer-sdk](https://github.com/meltano/sdk).

Updates `psycopg` from 3.2.6 to 3.2.7
<details>
<summary>Changelog</summary>
<p><em>Sourced from <a
href="https://github.com/psycopg/psycopg/blob/master/docs/news.rst">psycopg's
changelog</a>.</em></p>
<blockquote>
<p>.. currentmodule:: psycopg</p>
<p>.. index::
single: Release notes
single: News</p>
<h1><code>psycopg</code> release notes</h1>
<h2>Future releases</h2>
<p>Psycopg 3.3.0 (unreleased)
^^^^^^^^^^^^^^^^^^^^^^^^^^</p>
<ul>
<li>Drop support for Python 3.8.</li>
</ul>
<p>Psycopg 3.2.7
^^^^^^^^^^^^^</p>
<ul>
<li>Add SRID support to shapely dumpers/loaders
(:ticket:<code>[#1028](https://github.com/psycopg/psycopg/issues/1028)</code>).</li>
<li>Add support for binary hstore
(:ticket:<code>[#1030](https://github.com/psycopg/psycopg/issues/1030)</code>).</li>
</ul>
<p>Psycopg 3.2.6
^^^^^^^^^^^^^</p>
<ul>
<li>Fix connection semantic when using
<code>target_session_attrs=prefer-standby</code>

(:ticket:<code>[#1021](https://github.com/psycopg/psycopg/issues/1021)</code>).</li>
</ul>
<p>Psycopg 3.2.5
^^^^^^^^^^^^^</p>
<ul>
<li>3x faster UUID loading thanks to C implementation
(:tickets:<code>[#447](https://github.com/psycopg/psycopg/issues/447),
[#998](https://github.com/psycopg/psycopg/issues/998)</code>).</li>
</ul>
<p>Psycopg 3.2.4
^^^^^^^^^^^^^</p>
<ul>
<li>Don't lose notifies received whilst the
<code>~Connection.notifies()</code> iterator
is not running
(:ticket:<code>[#962](https://github.com/psycopg/psycopg/issues/962)</code>).</li>
<li>Make sure that the notifies callback is called during the use of the
<code>~Connection.notifies()</code> generator
(:ticket:<code>[#972](https://github.com/psycopg/psycopg/issues/972)</code>).</li>
<li>Raise the correct error returned by the database (such as
<code>!AdminShutdown</code>
or <code>!IdleInTransactionSessionTimeout</code>) instead of a generic
<code>OperationalError</code> when a server error causes a client
disconnection

(:ticket:<code>[#988](https://github.com/psycopg/psycopg/issues/988)</code>).</li>
<li>Build macOS dependencies from sources instead using the Homebrew
versions</li>
</ul>
<!-- raw HTML omitted -->
</blockquote>
<p>... (truncated)</p>
</details>
<details>
<summary>Commits</summary>
<ul>
<li><a
href="https://github.com/psycopg/psycopg/commit/a6a6317b0524cd0bdeff872b89e174716b90846d"><code>a6a6317</code></a>
Merge pull request <a
href="https://redirect.github.com/psycopg/psycopg/issues/1052">#1052</a>
from psycopg/connection-log</li>
<li><a
href="https://github.com/psycopg/psycopg/commit/62cd04d9cfef6c89791f51d40973ab190a6c2de9"><code>62cd04d</code></a>
chore: add connection debugging log in the C extension too</li>
<li><a
href="https://github.com/psycopg/psycopg/commit/55965e71b4bf4de56c5c6621ce5c9a91f1c8c3e0"><code>55965e7</code></a>
chore: add debug logging at connection time</li>
<li><a
href="https://github.com/psycopg/psycopg/commit/9266dc229a7ad58bf4bbd1afe47c3aba94155d24"><code>9266dc2</code></a>
fix: guard from unexpected connection status on repr</li>
<li><a
href="https://github.com/psycopg/psycopg/commit/cd7145b7af38f6a26c2af33f9e8e58227d2113b2"><code>cd7145b</code></a>
chore: bump psycopg package version to 3.2.7</li>
<li><a
href="https://github.com/psycopg/psycopg/commit/9e64699febea8789361a02315d65be7c1304746b"><code>9e64699</code></a>
feat: implement binary hstore protocol</li>
<li><a
href="https://github.com/psycopg/psycopg/commit/9d4142eb8346054db5dc73abcf03c5d0558f4cdc"><code>9d4142e</code></a>
test(pool): verify the overriding of <code>close()</code> to act as
<code>putconn()</code></li>
<li><a
href="https://github.com/psycopg/psycopg/commit/04630ebbf751e7ca5641328ede2739104aec5d4d"><code>04630eb</code></a>
test(crdb): add test reproducing failure with prepared create
statement</li>
<li><a
href="https://github.com/psycopg/psycopg/commit/f046b7f4114330e552d1e4b16f8a1ea17f0e3571"><code>f046b7f</code></a>
ci(crdb): pull stable crdb images from crdb docker repository</li>
<li><a
href="https://github.com/psycopg/psycopg/commit/5d7b377faf140c20e613a738f916d3bc3f2f54a6"><code>5d7b377</code></a>
style: define a symbolic const for null values in array</li>
<li>Additional commits viewable in <a
href="https://github.com/psycopg/psycopg/compare/3.2.6...3.2.7">compare
view</a></li>
</ul>
</details>
<br />

Updates `singer-sdk` from 0.45.3 to 0.45.11
<details>
<summary>Release notes</summary>
<p><em>Sourced from <a
href="https://github.com/meltano/sdk/releases">singer-sdk's
releases</a>.</em></p>
<blockquote>
<h2>v0.45.11 (2025-04-28)</h2>
<h3>🐛 Fixes</h3>
<ul>
<li><a
href="https://redirect.github.com/meltano/sdk/issues/3004">#3004</a>
Ensure fields with an array of JSON schema types are properly handled by
SQL targets</li>
<li><a
href="https://redirect.github.com/meltano/sdk/issues/2995">#2995</a> Pin
GitHub actions in templates</li>
<li><a
href="https://redirect.github.com/meltano/sdk/issues/2987">#2987</a> Add
a date to the warning message for removal of <code>Faker</code> from
stream maps contexts</li>
<li><a
href="https://redirect.github.com/meltano/sdk/issues/2982">#2982</a>
Allow streams to override <code>effective_schema</code> to apply schema
manipulations even on the input catalog</li>
</ul>
<h3>📚 Documentation Improvements</h3>
<ul>
<li><a
href="https://redirect.github.com/meltano/sdk/issues/3001">#3001</a>
Note <code>msgspec</code> extra as a prerequisite to using the
corresponding writer/reader classes -- <em><strong>Thanks <a
href="https://github.com/ReubenFrankel"><code>@​ReubenFrankel</code></a>!</strong></em></li>
</ul>
<h3>📦 Packaging changes</h3>
<ul>
<li><a
href="https://redirect.github.com/meltano/sdk/issues/2993">#2993</a>
Restore upper Python constraint for <code>backoff</code> dependency</li>
<li><a
href="https://redirect.github.com/meltano/sdk/issues/2981">#2981</a>
Constrain third-party <code>importlib-metadata</code> to &gt;=0.5.0</li>
</ul>
<h2>v0.45.10 (2025-04-16)</h2>
<h3>🐛 Fixes</h3>
<ul>
<li><a
href="https://redirect.github.com/meltano/sdk/issues/2978">#2978</a>
Restore private <code>_http_headers</code> attribute of REST
streams</li>
</ul>
<h2>v0.45.9 (2025-04-15)</h2>
<h3>🐛 Fixes</h3>
<ul>
<li><a
href="https://redirect.github.com/meltano/sdk/issues/2975">#2975</a>
Update cookiecutter templates</li>
<li><a
href="https://redirect.github.com/meltano/sdk/issues/2974">#2974</a> Do
not log a warning if <code>null</code> cannot be appended to schema
types</li>
<li><a
href="https://redirect.github.com/meltano/sdk/issues/2973">#2973</a>
Recognize <code>oneOf</code> fields in Singer schema helpers</li>
</ul>
<h2>v0.45.8 (2025-04-14)</h2>
<h3>🐛 Fixes</h3>
<ul>
<li><a
href="https://redirect.github.com/meltano/sdk/issues/2965">#2965</a>
<code>AttributeError: object has no attribute '_requests_session'</code>
when accessing public property during stream initialization --
<em><strong>Thanks <a
href="https://github.com/ReubenFrankel"><code>@​ReubenFrankel</code></a>!</strong></em></li>
<li><a
href="https://redirect.github.com/meltano/sdk/issues/2970">#2970</a>
Consider <code>oneOf</code> schemas when checking for <code>date</code>
and <code>datetime</code> types</li>
</ul>
<h2>v0.45.7 (2025-04-14)</h2>
<h3>🐛 Fixes</h3>
<ul>
<li><a
href="https://redirect.github.com/meltano/sdk/issues/2968">#2968</a>
<code>singer_sdk.singerlib.resolve_schema_references</code> now resolves
<code>oneOf</code> schema references</li>
<li><a
href="https://redirect.github.com/meltano/sdk/issues/2924">#2924</a>
Generate standard stream metadata for nested fields</li>
<li><a
href="https://redirect.github.com/meltano/sdk/issues/2940">#2940</a>
Ensure streams with hardcoded <code>schema</code> attributes (e.g. REST
and GraphQL streams) can have their schema overridden by the
catalog</li>
</ul>
<!-- raw HTML omitted -->
</blockquote>
<p>... (truncated)</p>
</details>
<details>
<summary>Changelog</summary>
<p><em>Sourced from <a
href="https://github.com/meltano/sdk/blob/main/CHANGELOG.md">singer-sdk's
changelog</a>.</em></p>
<blockquote>
<h2>v0.45.11 (2025-04-28)</h2>
<h3>🐛 Fixes</h3>
<ul>
<li><a
href="https://redirect.github.com/meltano/sdk/issues/3004">#3004</a>
Ensure fields with an array of JSON schema types are properly handled by
SQL targets</li>
<li><a
href="https://redirect.github.com/meltano/sdk/issues/2995">#2995</a> Pin
GitHub actions in templates</li>
<li><a
href="https://redirect.github.com/meltano/sdk/issues/2987">#2987</a> Add
a date to the warning message for removal of <code>Faker</code> from
stream maps contexts</li>
<li><a
href="https://redirect.github.com/meltano/sdk/issues/2982">#2982</a>
Allow streams to override <code>effective_schema</code> to apply schema
manipulations even on the input catalog</li>
</ul>
<h3>📚 Documentation Improvements</h3>
<ul>
<li><a
href="https://redirect.github.com/meltano/sdk/issues/3001">#3001</a>
Note <code>msgspec</code> extra as a prerequisite to using the
corresponding writer/reader classes -- <em><strong>Thanks <a
href="https://github.com/ReubenFrankel"><code>@​ReubenFrankel</code></a>!</strong></em></li>
</ul>
<h3>📦 Packaging changes</h3>
<ul>
<li><a
href="https://redirect.github.com/meltano/sdk/issues/2993">#2993</a>
Restore upper Python constraint for <code>backoff</code> dependency</li>
<li><a
href="https://redirect.github.com/meltano/sdk/issues/2981">#2981</a>
Constrain third-party <code>importlib-metadata</code> to &gt;=0.5.0</li>
</ul>
<h2>v0.45.10 (2025-04-16)</h2>
<h3>🐛 Fixes</h3>
<ul>
<li><a
href="https://redirect.github.com/meltano/sdk/issues/2978">#2978</a>
Restore private <code>_http_headers</code> attribute of REST
streams</li>
</ul>
<h2>v0.45.9 (2025-04-15)</h2>
<h3>🐛 Fixes</h3>
<ul>
<li><a
href="https://redirect.github.com/meltano/sdk/issues/2975">#2975</a>
Update cookiecutter templates</li>
<li><a
href="https://redirect.github.com/meltano/sdk/issues/2974">#2974</a> Do
not log a warning if <code>null</code> cannot be appended to schema
types</li>
<li><a
href="https://redirect.github.com/meltano/sdk/issues/2973">#2973</a>
Recognize <code>oneOf</code> fields in Singer schema helpers</li>
</ul>
<h2>v0.45.8 (2025-04-14)</h2>
<h3>🐛 Fixes</h3>
<ul>
<li><a
href="https://redirect.github.com/meltano/sdk/issues/2965">#2965</a>
<code>AttributeError: object has no attribute '_requests_session'</code>
when accessing public property during stream initialization --
<em><strong>Thanks <a
href="https://github.com/ReubenFrankel"><code>@​ReubenFrankel</code></a>!</strong></em></li>
<li><a
href="https://redirect.github.com/meltano/sdk/issues/2970">#2970</a>
Consider <code>oneOf</code> schemas when checking for <code>date</code>
and <code>datetime</code> types</li>
</ul>
<h2>v0.45.7 (2025-04-14)</h2>
<h3>🐛 Fixes</h3>
<ul>
<li><a
href="https://redirect.github.com/meltano/sdk/issues/2968">#2968</a>
<code>singer_sdk.singerlib.resolve_schema_references</code> now resolves
<code>oneOf</code> schema references</li>
<li><a
href="https://redirect.github.com/meltano/sdk/issues/2924">#2924</a>
Generate standard stream metadata for nested fields</li>
<li><a
href="https://redirect.github.com/meltano/sdk/issues/2940">#2940</a>
Ensure streams with hardcoded <code>schema</code> attributes (e.g. REST
and GraphQL streams) can have their schema overridden by the
catalog</li>
</ul>
<h3>📦 Packaging changes</h3>
<ul>
<li><a
href="https://redirect.github.com/meltano/sdk/issues/2966">#2966</a> Add
a <code>fallback-version</code> for hatch vcs</li>
</ul>
<!-- raw HTML omitted -->
</blockquote>
<p>... (truncated)</p>
</details>
<details>
<summary>Commits</summary>
<ul>
<li><a
href="https://github.com/meltano/sdk/commit/43b48bbe7d1e2731df91fcec6dcc683696b613d9"><code>43b48bb</code></a>
chore: Release v0.45.11 (<a
href="https://redirect.github.com/meltano/sdk/issues/3005">#3005</a>)</li>
<li><a
href="https://github.com/meltano/sdk/commit/260bcf1dd0dd2c877a8b73bbdfecc6d9dfceb89a"><code>260bcf1</code></a>
fix(targets): Ensure fields with an array of JSON schema types are
properly h...</li>
<li><a
href="https://github.com/meltano/sdk/commit/9fe2c5f9b00e8d3bbd2e694c6c0ad97dcdd9c93e"><code>9fe2c5f</code></a>
chore: Lock file maintenance (<a
href="https://redirect.github.com/meltano/sdk/issues/3003">#3003</a>)</li>
<li><a
href="https://github.com/meltano/sdk/commit/de299d94282e0f6d07ffa844414c1daee3524965"><code>de299d9</code></a>
chore(deps): bump the actions group with 4 updates (<a
href="https://redirect.github.com/meltano/sdk/issues/3002">#3002</a>)</li>
<li><a
href="https://github.com/meltano/sdk/commit/5273f325bd518842290e16673fc33f26c245f1b0"><code>5273f32</code></a>
chore: Update bug issue template</li>
<li><a
href="https://github.com/meltano/sdk/commit/b9196aae24aba05432ff1de376f905c44c102ed7"><code>b9196aa</code></a>
docs: Note <code>msgspec</code> extra as a prerequisite to using the
corresponding write...</li>
<li><a
href="https://github.com/meltano/sdk/commit/dc7fd0d139dbdefbc291772d777d6d3e3c8b941b"><code>dc7fd0d</code></a>
chore: Lock file maintenance (<a
href="https://redirect.github.com/meltano/sdk/issues/2996">#2996</a>)</li>
<li><a
href="https://github.com/meltano/sdk/commit/0d52585d7175e35982b469eb46ecb1768a0cba60"><code>0d52585</code></a>
fix(templates): Pin GitHub actions in templates (<a
href="https://redirect.github.com/meltano/sdk/issues/2995">#2995</a>)</li>
<li><a
href="https://github.com/meltano/sdk/commit/c152403ba539a11d0d2b4a699c0885b31d4c7567"><code>c152403</code></a>
packaging: Restore upper Python constraint for <code>backoff</code>
dependency (<a
href="https://redirect.github.com/meltano/sdk/issues/2993">#2993</a>)</li>
<li><a
href="https://github.com/meltano/sdk/commit/10f580cb76c9807124a785bd5e11ca0102d02e0d"><code>10f580c</code></a>
chore: pre-commit autoupdate (<a
href="https://redirect.github.com/meltano/sdk/issues/2991">#2991</a>)</li>
<li>Additional commits viewable in <a
href="https://github.com/meltano/sdk/compare/v0.45.3...v0.45.11">compare
view</a></li>
</ul>
</details>
<br />


Dependabot will resolve any conflicts with this PR as long as you don't
alter it yourself. You can also trigger a rebase manually by commenting
`@dependabot rebase`.

[//]: # (dependabot-automerge-start)
[//]: # (dependabot-automerge-end)

---

<details>
<summary>Dependabot commands and options</summary>
<br />

You can trigger Dependabot actions by commenting on this PR:
- `@dependabot rebase` will rebase this PR
- `@dependabot recreate` will recreate this PR, overwriting any edits
that have been made to it
- `@dependabot merge` will merge this PR after your CI passes on it
- `@dependabot squash and merge` will squash and merge this PR after
your CI passes on it
- `@dependabot cancel merge` will cancel a previously requested merge
and block automerging
- `@dependabot reopen` will reopen this PR if it is closed
- `@dependabot close` will close this PR and stop Dependabot recreating
it. You can achieve the same result by closing it manually
- `@dependabot show <dependency name> ignore conditions` will show all
of the ignore conditions of the specified dependency
- `@dependabot ignore <dependency name> major version` will close this
group update PR and stop Dependabot creating any more for the specific
dependency's major version (unless you unignore this specific
dependency's major version or upgrade to it yourself)
- `@dependabot ignore <dependency name> minor version` will close this
group update PR and stop Dependabot creating any more for the specific
dependency's minor version (unless you unignore this specific
dependency's minor version or upgrade to it yourself)
- `@dependabot ignore <dependency name>` will close this group update PR
and stop Dependabot creating any more for the specific dependency
(unless you unignore this specific dependency or upgrade to it yourself)
- `@dependabot unignore <dependency name>` will remove all of the ignore
conditions of the specified dependency
- `@dependabot unignore <dependency name> <ignore condition>` will
remove the ignore condition of the specified dependency and ignore
conditions


</details>

Signed-off-by: dependabot[bot] <support@github.com>
Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>